const samplePortfolio = [
    {
        name: "PWA Text Editor",
        details: "A demonstration of an installable, optimised Web App",
        GitHubLink: "https://github.com/rtrevill/PWA-Text-Editor",
        image: '/PWA.webp',
        deployLink: 'https://pacific-lowlands-90183-3e021944b31d.herokuapp.com/',
    },
    {
        name: "NoSQL-basic-social-net ",
        details: "A basic social media application that utilises MongoDB and Mongoose",
        GitHubLink: "https://github.com/rtrevill/NoSQL-basic-social-net",
        image: '/mongodb-logo2.webp',
        deployLink: '',
    },
    {
        name: "Regex Tutorial",
        details: "A tutorial gist in GitHub to decypher regular expressions",
        GitHubLink: "https://github.com/rtrevill/Regex-tutorial",
        image: '/regex.avif',
        deployLink: '',
    },
    {
        name: "MVC-tech-blog",
        details: "A simple blog application where users can make comments, and then chat on those comments",
        GitHubLink: "https://github.com/rtrevill/MVC-tech-blog",
        image: '/MVC2.png',
        deployLink: 'https://tech-blog-rtrevill-90d64a3bf7f0.herokuapp.com/',
    },
    {
        name: "Personal-Portfolio-Site",
        details: "My first attempt at a portfolio site using only HTML, CSS and JS",
        GitHubLink: "https://github.com/rtrevill/Personal-Portfolio-Site",
        image: '/Portfolio.png',
        deployLink: '',
    },
    {
        name: "Back-end-API-for-Ecommerce",
        details: "A back-end only demonstration of using SQL2 DB and creating routes to GET and modify data",
        GitHubLink: "https://github.com/rtrevill/Back-end-API-for-Ecommerce",
        image: '/orm.jpg',
        deployLink: '',
    },
    {
        name: "Staff-Tracker",
        details: "A back-end demonstration of using SQL to manipulate data tables",
        GitHubLink: "https://github.com/rtrevill/Staff-Tracker",
        image: '/SQL.jpg',
        deployLink: '',
    },
    {
        name: "NotesAndTasks",
        details: "A note taking application where you can create and remove tasks",
        GitHubLink: "https://github.com/rtrevill/NotesAndTasks",
        image: '/ExpressJS.png',
        deployLink: 'https://notes-to-rememb-7ddf23d50c32.herokuapp.com/',
    },
    {
        name: "svg-creator ",
        details: "A command line application where users select shapes, colours and text to create a custom SVG",
        GitHubLink: "https://github.com/rtrevill/svg-creator",
        image: '/OOP.webp',
        deployLink: '',
    },
    {
        name: "Pro-ReadMe-Generator",
        details: "A back end application that automatically creates a usable Readme.md file based on user input",
        GitHubLink: "https://github.com/rtrevill/Pro-ReadMe-Generator",
        image: '/NodeJS.png',
        deployLink: '',
    },
    {
        name: "Web-Dev_Proj1",
        details: "My first group project. This is a recipe finder application that also provides nutritional information, and links to wikipedia pages on any of the ingredients",
        GitHubLink: "https://github.com/rtrevill/Web-Dev_Proj1",
        image: '/munchies1.png',
        deployLink: '',
    },
    {
        name: "Dynamic-Weather-Dashboard",
        details: "A weather forecasting application to demonstrate API calls",
        GitHubLink: "https://github.com/rtrevill/Dynamic-Weather-Dashboard",
        image: '/API.jpg',
        deployLink: '',
    },
    {
        name: "Daily-Meeting-Planner",
        details: "A sceduling application where users can enter times of appointments, and this gets saved to local storage",
        GitHubLink: "https://github.com/rtrevill/Daily-Meeting-Planner",
        image: '/JQuery.png',
        deployLink: '',
    },
    {
        name: "Coding-Quiz ",
        details: "A brief game where users guess the answer to quiz questions as quick as possible",
        GitHubLink: "https://github.com/rtrevill/Coding-Quiz",
        image: '/Quiz.png',
        deployLink: '',
    },
    {
        name: "rtrevill-password-generator",
        details: "A small application that creates customised passwords based on user criteria",
        GitHubLink: "https://github.com/rtrevill/rtrevill-password-generator",
        image: '/Password.png',
        deployLink: '',
    },
]


export default samplePortfolio;